### PR TITLE
DB-9930: Add TRANSLATION_NOT_FOUND

### PR DESCRIPTION
**Pull request by pyusimocient**
https://jira.ocient.com:8443/browse/DB-9930

### CODE REVIEW

**Comment by pyusimocient** [comment]
@leogreca would you take a look at this PR please? Let me know if there are any issues.

**Comment by leogreca** [comment]
Hi Pavel, 
PR looks good. 

Now the question is: What is your rush for this change to go in the next driver release. 
1- No rush. It is fine that this change is released in a month or so. 
If that is the case, let's just merge it and we are good. 

2- You want it soon. 
If that is the case, you will have to do a driver release. Those are the steps:
`
xgsrc/xgjdbc (user/leo/arrayDoc)$ cat readMeOnHowToDeployANewJdbcBuild.txt
1- In the ocient_jdbc repo root:
1.1 - increment the jdbc version in: ./ocient_jdbc/pom.xml
1.2 - type 'mvn package' in the root directory
1.3 - check if the version number is correct by running: NEW_VERSION_NUMBER=<your_version_here> unzip -p ./ocient_jdbc/target/ocient-jdbc4-${NEW_VERSION_NUMBER}-jar-with-dependencies.jar | head
2-  NEW_VERSION_NUMBER=<your_version_here> ; mkdir v${NEW_VERSION_NUMBER} ; cp ocient-jdbc4-${NEW_VERSION_NUMBER}-jar-with-dependencies.jar v${NEW_VERSION_NUMBER} ; scp -r v${NEW_VERSION_NUMBER} user@ocient-archive:/home/user/www/ocientrepo/java/jdbc/ && rm -r v${NEW_VERSION_NUMBER}
3- In the xgsrc repo, increment the version number in xgsrc/xgjdbc/Makefile to point to the created directory.
`

**Comment by pyusimocient** [comment]
@leogreca the corresponding change is just going into our feature branch, so no at all, let's just merge it.

**Comment by leogreca** [comment]
I will ask Jason to merge it then.

**Pull request merged**
